### ISSUE TITLE
YES and NO shouldn't be quoted in px-file

### ISSUE THREAD

**Issue by johan-ejstrud** [StatisticsGreenland/pxmake#118]

**Comment by johan-ejstrud** [comment]
This is only present in BEXLTALL which has elimination = YES
![image](https://user-images.githubusercontent.com/11992346/228851817-b6809dff-1bb9-48f1-bb08-4a1cf14ddc1d.png)

Maybe that should actually be quoted?

**Comment by larpSTATGL** [comment]
No quotes on YES/NO but quotes if set to a value in codelist
