### ISSUE TITLE
Add VARIABLE-TYPE

### ISSUE THREAD

**Issue by johan-ejstrud** [StatisticsGreenland/pxmake#125]
Limited documentation:
![image](https://user-images.githubusercontent.com/11992346/228513882-1df2e6f0-b4d4-4b07-80db-7b9c3a842546.png)

Example from Faroe Islands:
![image](https://user-images.githubusercontent.com/11992346/228514298-120e4ecd-fc13-41fb-98bc-703714ea4145.png)

**Comment by larpSTATGL** [comment]
Petros wrote:

The keyword VARIABLECODE could look like this

VARIABLECODE("Gender") ="sex"
VARIABLECODE[sv]("Kön") ="sex"
The "key" is the variable name and if it is multilingual file you should repeat it for every language but the value of the code should be the same for languages. It is kind of strange but it is similar solution as for the value codes.

There is a VARIABLETYPE keyword. That is a open text filed.
But in the work of the API we have standardise some codes
T for time
G for geographical
C for contents
