### ISSUE TITLE
tjek og spring over code/tekster som ikke findes i DATA, men kun Codelists_2md

### ISSUE THREAD

**Issue by larpSTATGL** [StatisticsGreenland/pxmake#13]
tjek og spring over code/tekster som ikke findes i DATA, men kun Codelists_2md

fejler pt

**Comment by johan-ejstrud** [comment]
Opgave
- [ ] Lav eksempel blandt testcases

**Comment by johan-ejstrud** [comment]
Closed because of 3d20785352074b640b8f4b97ec0978478e4831f4
