### ISSUE TITLE
missing keywords - Norwegian example

### ISSUE THREAD

**Issue by larpSTATGL** [StatisticsGreenland/pxmake#138]
Did a saved query from statNorway and found keyword not handled in 0.5.2. Metamake still does good, but of cause doesn't handle the keywords listed in example below. With some editing of the xlsx it works.

Also VARIABLE-TYPE (G, V and T) is used

library(tidyverse)
library(pxmake)

workPath <- file.path(getwd(),"tmp")

'# Data source SSB.no, saved query. Open this link in browser to see: https://www.ssb.no/statbank/sq/10080591 

'# Get as px-file, save to disk
read_file(https://www.ssb.no/statbank/sq/10080591.px) %>% 
  write_file(file.path(workPath,"oslo.px"))

'# Convert into xlsx
metamake(file.path(workPath,"oslo.px"),
         file.path(workPath,"oslo_by_metamake.xlsx"))

CONTVARIABLE="statistikkvariabel";
PRESTEXT("region")=2;
PRESTEXT("år")=0;
MAP("region")="Norge_Bydel";
STOCKFA("Personer")="S";
DAYADJ("Personer")=NO;
SEASADJ("Personer")=NO;
REFPERIOD("Personer")="1.1.";
DATABASE="Ekstern PRODUKSJON";
INFOFILE="None";
META-ID="KORTNAVN:folkemengde";
META-ID("region")="urn:ssb:classification:klass:103";
META-ID("alder")="urn:ssb:classification:klass:282";
META-ID("kjønn")="urn:ssb:classification:klass:2";
DATASYMBOL1="..";
DATASYMBOL2="...";
DATASYMBOL3=":";
DATASYMBOLSUM=".";
DATASYMBOLNIL="-";
DATANOTESUM=".";
VARIABLE-TYPE("region")="G";
VARIABLE-TYPE("alder")="V";
VARIABLE-TYPE("år")="T";
VARIABLE-TYPE("kjønn")="V";

CONTVARIABLE[en]="contents";
VARIABLECODE[en]("region")="Region";
PRESTEXT[en]("region")=2;
PRESTEXT[en]("year")=0;
MAP[en]("region")="Norge_Bydel";
STOCKFA[en]("Persons")="S";
DAYADJ[en]("Persons")=NO;
SEASADJ[en]("Persons")=NO;
REFPERIOD[en]("Persons")="1.1.";
DATABASE[en]="External PROD";
DATANOTESUM[en]=".";
VARIABLE-TYPE[en]("region")="G";
VARIABLE-TYPE[en]("age")="V";
VARIABLE-TYPE[en]("year")="T";
VARIABLE-TYPE[en]("sex")="V";

**Comment by johan-ejstrud** [comment]
Closing. We should add issues for the individual keywords that are missing.
