### ISSUE TITLE
contvariable add

### ISSUE THREAD

**Issue by larpSTATGL** [StatisticsGreenland/pxmake#175]
Jeg prøvede, at tilføje CONTVARIABLE til en px fil i pxedit og så danne meta med metamake, for så at afslutte med pxmake

Og det FUNKER 😊

Så nu er spørgsmålet om ikke vi skal have en add_contvariable agtig funktion – når man har en rds i memory? For at hjælpe med at danne ikke-eksisterende metadata

add_contvariable <- function(variable){
  rds <- rds$metadata %>% 
  mutate()%>%
  rbind(……)
}

**Comment by johan-ejstrud** [comment]
Duplicate #223

**Comment by johan-ejstrud** [comment]
Closed by [1875590](https://github.com/StatisticsGreenland/pxmake/commit/1875590ac85075c8116ec39fd61f4c87dad4a4eb)
