### ISSUE TITLE
Let ELIMINATION be 'YES' or code of elimination value

### ISSUE THREAD

**Issue by johan-ejstrud** [StatisticsGreenland/pxmake#180]
Currently ELIMINATION has to be specified by writing the variable label for all languages in the file. This is errorprone, and unnessasary since the levels are already specified in 'Codelists'.

Instead ELIMINATION should be collapsed to one column an be either YES or the code of the value that should be used to eliminate.

**Comment by larpSTATGL** [comment]
CODES are not mandatory, VALUES are

**Comment by johan-ejstrud** [comment]
> CODES are not mandatory, VALUES are

Okay, I think I had that the wrong way around. Do we need to do any change because of that?

**Comment by johan-ejstrud** [comment]
This shouldn't be changed.
