### ISSUE TITLE
px-file cannot be opened by PXweb (version 22)

### ISSUE THREAD

**Issue by johan-ejstrud** [StatisticsGreenland/pxmake#196]
Issue repported by Michael Feldballe,

A px-file generated by pxmake gives following error when opened in PXweb (versions 22):
`“Cannot search [path]. Object reference not set to an instance of an object.”`

The issues is resolved by opening the px-file in px-edit and saving it again.

Attached is the file directly from pxmake and from pxedit:

[from_pxmake.txt](https://github.com/StatisticsGreenland/pxmake/files/14096579/from_pxmake.txt)
[pxedit_after_pxmake.txt](https://github.com/StatisticsGreenland/pxmake/files/14096580/pxedit_after_pxmake.txt)

**Comment by johan-ejstrud** [comment]
Michael I think the issue is in the `TIMEVAL` keyword. 

In the file generated by pxmake it looks like this:

```TIMEVAL("Year")=TLIST(A1)","2007","20...```

which is wrong. From the px-file specification it should look like this:
![image](https://github.com/StatisticsGreenland/pxmake/assets/11992346/359cdf9b-3e1a-4eb5-8143-14f02c37fe32)

There is an extra `"` after `TLIST(A1)` which I assume breaks "something". 

It looks like PX-Edit silently fixes this by removing the extra `"`:

`TIMEVAL("Year")=TLIST(A1),"2007","20...`

Michael can I get you to test the following file on your server? It's exactly like the file `A_PX.px` you sent, except that I have removed the extra `"`. You might need to change the file extension to `.px`.
[from_pxmake_remove_extra_quote.txt](https://github.com/StatisticsGreenland/pxmake/files/14096699/from_pxmake_remove_extra_quote.txt)

**Comment by Feldballe** [comment]
Thank you for the update.
I did make at copy of the txt-file, changed the file-type, and prepared a test on the server. Beforehand I made a copy of the file using PXEdit 4.0 and uploaded to two different PX-databases. 
The one file that was saved using PXEdit did ok. The other one returned a warning in the creation proces ending with the text "{0} error" after the px filename. 
The PX-server log does not report any error or information differnet between the two files, so I am not able to provide any further information as to why the PX-server did not create the database.

**Comment by johan-ejstrud** [comment]
Thanks @Feldballe, I'll take a more thorough look at this tommow.

**Comment by Feldballe** [comment]
I have made modifications to the original file from pxmake, identical to the px-edit version of the same, and I ran them both through Notepad++ to see if there are any differences.
And I noticed that a " i missing in the end of TIMEVAL definition:
TIMEVAL("Year")=TLIST(A1),"2007","2008","2009","2010","2011","2012","2013","2014","2015","2016",
"2017","2018","2019","2020","2021","2022;

**Comment by johan-ejstrud** [comment]
Great @Feldballe!

I will close this issue, and make sure that it doesn't exist in the next version 0.10. 😊
