### ISSUE TITLE
Add save_date argument to pxsave

### ISSUE THREAD

**Issue by johan-ejstrud** [StatisticsGreenland/pxmake#204]
`pxsave()` should have the same argumnets as `metamake` that makes it possible to supress data generation or redirect the 'Data' sheet in Excel to an `.rds` file.

![image](https://github.com/StatisticsGreenland/pxmake/assets/11992346/31d92ed6-b483-4146-9d27-59148e4a8461)

**Comment by larpSTATGL** [comment]
Save_data ?

**Comment by johan-ejstrud** [comment]
@larpSTATGL I have added more info to the issue description. 😁

**Comment by larpSTATGL** [comment]
when reading a xlsx without the data sheet I get:

+   pxsave("test.xlsx",save_data = FALSE)
>  b <- px("test.xlsx")
Fejl: The sheet 'Data' is missing in: test_Modified.xlsx.

**Comment by johan-ejstrud** [comment]
@larpSTATGL 
Currently it's not possible to create a px object wihtout a data table. When the data is not stored in excel one needs to use the `data=` argument to specify a path to a data set. E.g.:

`px('test.xlsx', data = 'test.rds')`

I just had a quick look at the code, and it might be possible that we can create px objects, even though theres's no data table. It's just not supported a the moment, and that's why px gives an error.
