### ISSUE TITLE
Convert sortorder to number

### ISSUE THREAD

**Issue by johan-ejstrud** [StatisticsGreenland/pxmake#23]

**Comment by johan-ejstrud** [comment]
Det er ikke sikkert det her er nødvendigt? Når jeg ændrer i sortorder, bliver det ændret rigtig i px filerne, selvom vi ikke sorterer på sortorder. 

Man kan også overveje: 
1. Om vi automatisk bør tilføje labels hvis de er det samme som code,,
2. Om sortorder, som udgangspunkt bør være sorteringen af code, og så kan man tilføje sortorder hvis man vil ændre i sorteringen.

**Comment by johan-ejstrud** [comment]
@larpSTATGL laver tests

**Comment by johan-ejstrud** [comment]
> Nu bliver rækkefølge i px-fil samme rækkefølge som codelist står i, hvis der ikke er en sortorder. Der sorteres ikke efter code. Hvis sortorder er sat sorteres fint efter den.

Hvis sortorder ikke står der, synes jeg også, at det lyder som en god ide, at bibeholde rækkefølgen i arken, fremfor at sortere code alfabetisk. I så fald skal vi også lukke #22 ?

Har du testet hvad der sker, hvis sortorder er tastet ind i Excel som tekst?

**Comment by johan-ejstrud** [comment]
Har du testet hvad der sker, hvis sortorder er tastet ind som tekst i Excel? 

Jeg frygter at det her ville blive sorteret 1, 10, 2, og derfor a, c, b.

| code | sortorder | 
| ------|-------| 
| a | 1 | 
| b | 2 | 
| c | 10 |

**Comment by larpSTATGL** [comment]
![image](https://user-images.githubusercontent.com/14994906/224016464-e3138939-402a-42b4-9f6a-7d5dbc0fd7a4.png)


![image](https://user-images.githubusercontent.com/14994906/224017087-240c7692-fe25-4896-99cc-cc86631292ac.png)

![image](https://user-images.githubusercontent.com/14994906/224017366-9d660430-75f6-45e6-be0c-3973030906b5.png)

![image](https://user-images.githubusercontent.com/14994906/224017943-ba89c4d1-5418-4018-8840-7341f3702e9a.png)
