### ISSUE TITLE
last_updated

### ISSUE THREAD

**Issue by larpSTATGL** [StatisticsGreenland/pxmake#232]
If last_updated keyword exists last_updated function shall update keyword - not add . perhaps a general issue?

**Comment by johan-ejstrud** [comment]
`last_updated(x, value = 'yyymmdd  hh:mm')` should update the value no matter if LAST-UPDATED is already set or not.

Can you add an example of this not working?

**Comment by larpSTATGL** [comment]
too big - lets share screen

**Comment by johan-ejstrud** [comment]
This is a bug: #233
