### ISSUE TITLE
Name collisions

### ISSUE THREAD

**Issue by johan-ejstrud** [StatisticsGreenland/pxmake#254]
## Problem
We have some bad name collisions with functions from popular packages:

![image](https://github.com/StatisticsGreenland/pxmake/assets/11992346/4113ad98-32a1-4dfe-a044-ca5c864647e2)

This will be exacerbated by these functions that are not yet implemented:

- DATA
- ORDER
- SOURCE
- ORDER

### 1. Add a prefix in front of _all_ px modifying functions. 

Examples:

- `px`
   - pxcodepage
   - pxheading
   - pxmap
   - pxunits
   - pxlanguage
- `px_`
   - px_codepage
   - px_heading
   - px_map
   - px_units
   - px_language
 - `x`
    - xcodepage
    - xheading
    - xmap
    - xunits
    - xlanguage

Disadvange: Makes it slower to type name of functions.

### 2. Add a prefix only in front of functions with name collitions.

- `px_`
   - codepage
   - heading
   - px_map
   - units
   - language

Disadvangte: Makes naming inconsistent.

**Comment by larpSTATGL** [comment]
I think my preference would be consistent px_ prefix

**Comment by johan-ejstrud** [comment]
I also prefer the `px_` prefix. 

I'll get it done.
