### ISSUE TITLE
error in px-file, sortorder of values/codes 

### ISSUE THREAD

**Issue by larpSTATGL** [StatisticsGreenland/pxmake#258]
using pxsave the sortorder of values/codes is alphabetic. Shall be order as defined by stub/heading in 

x$variables1 %>% pull(order)

**Comment by johan-ejstrud** [comment]
Hey @larpSTATGL I cannot reproduce this.

Here's a minimal example where I reverse the order:

```r
library(tidyverse)
library(pxmake)

x <- px(women)

reverse_order <-
  x$codelists1 %>% 
  arrange(desc(order)) %>% 
  mutate(order = row_number()) %>% 
  select(`variable-code`, code, order)

x_reverse <-
  x %>% 
  order(reverse_order)

pxsave(x,               'women.px')
pxsave(x_reverse, 'women_reverse.px')
```

When I open the two saved files in PxEdit the order is correctly reversed.

Please try my example and see if you agree. If you do, try to take your code, and make the smallest possible example where you still get the wrong output, then I can have a look at it. 😊

**Comment by larpSTATGL** [comment]
> x <- px(women)
> reverse_order <-
+   x$codelists1 %>% 
+   arrange(desc(order)) %>% 
+   mutate(order = row_number()) %>% 
+   select(`variable-code`, code, order)
> x_reverse <-
+   x %>% 
+   order(reverse_order)
Fejl i rank(x, ties.method = "min", na.last = "keep") : 
  unimplemented type 'list' in 'greater'

**Comment by johan-ejstrud** [comment]
Den tager `order` fra base i stedet for pxmake tror jeg. 

Prøv:
```
library(tidyverse)
library(pxmake)

x <- px(women)

reverse_order <-
  x$codelists1 %>% 
  arrange(desc(order)) %>% 
  mutate(order = row_number()) %>% 
  select(`variable-code`, code, order)

x_reverse <-
  x %>% 
  pxmake::order(reverse_order)

pxsave(x,               'women.px')
pxsave(x_reverse, 'women_reverse.px')
```

**Comment by larpSTATGL** [comment]
ok - I am on today
> packageVersion('pxmake')
[1] ‘0.10.1.9005’

I'll make our server update tonight

thanx - expect it will do magick

**Comment by larpSTATGL** [comment]
:-)

**Comment by johan-ejstrud** [comment]
I hope so too 😁🤞
