### ISSUE TITLE
The wrong variable is chosen as figures

### ISSUE THREAD

**Issue by gnpe-nuuk** [StatisticsGreenland/pxmake#300]
It is the last variable that is selected, not the variable with the figures

see this example:

```
library(tidyverse)
library(pxmake)

#out:
statgsbank_path <- file.path("S:","STATGS","AR","bank","pxmake test")
px_name <- "test"

dta <- greenlanders %>%
  count(gender, municipality, name = "antal") %>%
  select(gender, antal, municipality) #change the order of variables

pxobj <- px(dta)

px_save(pxobj,
        file.path(statgsbank_path, "results", paste0(px_name, "_by_metamake.xlsx")),
        save_data = FALSE
)
```

**Comment by johan-ejstrud** [comment]
> It is the last variable that is selected, not the variable with the figures

You are right. 

When there is no metadata, pxmake has no way of knowing which variable contains figures, and it therefore chooses the last column as default. (it also chooses the second last as HEADING, and all the remaining columns as STUB).

To overwrite this, simply state which variable contains figures, right after you create the px object:

```
dta <- greenlanders %>%
  count(gender, municipality, name = "antal") %>%
  select(gender, antal, municipality) #change the order of variables

pxobj <- 
  px(dta) %>% 
  px_figures('antal')
```

Does this work for you?

And thanks the detailed exampled.

**Comment by gnpe-nuuk** [comment]
It working, but sheet “Cells” is not changes.

I have corrected my program
pxobj <- px(dta) %>%
  px_figures("antal") %>%
  px_heading("municipality")

Fra: johan-ejstrud ***@***.***>
Sendt: torsdag den 27. juni 2024 09.55
Til: StatisticsGreenland/pxmake ***@***.***>
Cc: Gorm N. Pedersen ***@***.***>; Author ***@***.***>
Emne: Re: [StatisticsGreenland/pxmake] The wrong variable is chosen as figures (Issue #300)


It is the last variable that is selected, not the variable with the figures

You are right.

When there is no metadata, pxmake has no way of knowing which variable contains figures, and it therefore chooses the last column as default. (it also chooses the second last as HEADING, and all the remaining columns as STUB).

To overwrite this, simply state which variable contains figures, right after you create the px object:

dta <- greenlanders %>%

  count(gender, municipality, name = "antal") %>%

  select(gender, antal, municipality) #change the order of variables



pxobj <-

  px(dta) %>%

  px_figures('antal')

Does this work for you?

And thanks the detailed exampled.

**Comment by johan-ejstrud** [comment]
> It working, but sheet “Cells” is not changes.

That is true. Ideally the `variable-code=n` values in cells and cells2 should be filtered about. 

Do you get any further errors, or does it work? I will consider adding a step that filteres these value out when figures is changed,

**Comment by gnpe-nuuk** [comment]
px_timeval is the same, the time variable is not removed from cells

**Comment by johan-ejstrud** [comment]
I have closed this issue, and create a shorter one that only describes what needs to be changed: #304
