### ISSUE TITLE
Få px_elimination til at sætte elimination for STUB/HEADING variable, ikke alle variable

### ISSUE THREAD

**Issue by larpSTATGL** [StatisticsGreenland/pxmake#325]
jeg tænker dette kunne være et godt start eksempel hvor det bygges op trin for trin - og uden forstyrrende elementer åbne med pxwin

library(tidyverse)
library(pxmake)

diamonds <- ggplot2::diamonds %>% 
  select(carat,cut,color,clarity) %>% 
  count(across(everything()))

px(diamonds) %>%
  px_elimination('Total') %>% 
 px_add_totals(c("carat","cut","color","clarity")) %>% 
  px_save("test.px")

**Comment by larpSTATGL** [comment]
Super eksempel. 👌

hvordan undgør jeg enklest at denne kode også danne elimination for tællevariable 'n'?

Som pxmake virker nu, ville du være nødt til eksplicit at skrive de variable, der skal have elimination: 

px(diamonds) %>% 
  px_elimination(tribble(~`variable-code`, ~elimination,
                         "carat",     "Total",
                         "cut",       "Total",
                         "color",     "Total",
                         "clarity",   "Total"
                         )
                 ) %>% 
  px_add_totals(c("carat","cut","color","clarity")) %>% 
  px_save("test.px")

Det synes jeg ikke er særlig smart. Jeg tror vi skal lave en ændring.

Giver det nogensinde mening at have en ELIMINATION værdi for figur variablen? 🤔

Det tror jeg ikke, og i så fald synes jeg simpelthen vi skal ændre px_elimination. Faktisk tror jeg, at vi skal lave to ændringer:

px_elimination('value') skal sætte ELIMINATION for alle STUB og HEADING variable, i stedet for alle variable.
Hvis ikke der er sat nogen px_elimination, så skal px_add_totals automatisk sætte elimination til 'Total' for de variable der får tilføjet et total level.

Hvis vi implementerer 1. ville din originale kode virke perfekt.
Hvis vi også implementerer 2. ville du helt kunne spare px_elimination, så koden bare bliver til:

px(diamonds) %>%
  px_add_totals(c("carat","cut","color","clarity")) %>% 
  px_save("test.px")

**Comment by larpSTATGL** [comment]
Jeg tror 1 er nok
 
Det giver mulighed for progression i introduktion – Og man kunne gøre det ene uafhængigt af det andet
 
Fx sætte elimination=YES
 
Så enig aldrig Total på figures_var
 
Og ej heller Total på den som er defineret som TIMEVAL

**Comment by larpSTATGL** [comment]
https://stat.gl/pxmake/pxwinr.html

**Comment by larpSTATGL** [comment]
jeg tænker at vise den på torsdag :-)

**Comment by johan-ejstrud** [comment]
**@larpSTATGL vil man nogensinde sætte DOMAIN eller MAP for en figures variabel?**

Jeg tror det ikke, og i så fald giver det mening at lave samme ændring for `px_domain` og `px_map`, nemlig, at de kun sættes for STUB og HEADING. Det gør det også lettere at implementere. 😊

**Comment by larpSTATGL** [comment]
great :-)
