### ISSUE TITLE
px_precision doesn't work anymore

### ISSUE THREAD

**Issue by gnpe-nuuk** [StatisticsGreenland/pxmake#337]
px("file.px")) %>% px_precision() is empty (pxmake version 0.12.1.9004)

v0.12.0 is working

**Comment by johan-ejstrud** [comment]
@gnpe-nuuk 

That's strange. 🤔

**Can you upload the specific px-file here so I can have a better look at it?**

**Comment by gnpe-nuuk** [comment]
https://bank.stat.gl:443/sq/7e1dca63-380d-4131-aa32-64aa237f5ffe

**Comment by johan-ejstrud** [comment]
@gnpe-nuuk 

**This has now been fixed in version 0.12.1.9005.**

When adding support for CELLNOTE I accidentally introduced the bug you discovered.

I tested with your file, and it seems to work now.

Thanks for the bug report. 😁
