### ISSUE TITLE
Metadata mangler det mandatory keyword TITLE

### ISSUE THREAD

**Issue by johan-ejstrud** [StatisticsGreenland/pxmake#47]
Det ser ud til at PXJOB bruger DESCRIPTION som TITLE, hvis den ikke eksisterer.

**Comment by larpSTATGL** [comment]
TITLE dannes dynamisk ud fra indhold i CONTENTS samt valgte variable. Dvs hvis bruger vælger tid + 2 variabler fra en tabel med +2 variabler bliver titel= content (fordelt efter) variabel 1 (og) variabel 2 - tekst i parantes er sprogafhængig

Description er fast. det er den tekst som vises i statbank menuer.

Hvis TITLE ikke eksisterer er det fint at sætte den lig DESCRIPTION og hvis den ikke eksisterer lig CONTENT

**Comment by johan-ejstrud** [comment]
Tak @larpSTATGL 

2 spørgsmål:

1. Er vi okay med ikke at `pxmake()` ikke danner TITLE, og i stedet lader PxJob gøre det?
1. Vil vi gerne have at `pxmake()` danner alle de [mandatory keywords](https://scb.se/en/services/statistical-programs-for-px-files/px-file-format/mandatory-keywords/), eller må vi godt undlade nogle af dem?

**Comment by johan-ejstrud** [comment]
Title is created automatically when a dataset is used as input in px(). Adding it automatically for broken px files is a job for #212
