### ISSUE TITLE
Lav Excel template ud fra data på statistikbanken

### ISSUE THREAD

**Issue by johan-ejstrud** [StatisticsGreenland/pxmake#61]
Brug en url til en online tabel og brug den til at prepopulere et Excel template.

**Comment by johan-ejstrud** [comment]
Relateret til #16

**Comment by larpSTATGL** [comment]
@johan-ejstrud jeg har lagt en ny markdown op under R/future. Med hjælp fra Daniel hentes nu metadata om variabler fra en eksisterende statbank tabel + et eksempl på hent fra Hagstova.fo
