### ISSUE TITLE
Del General metadata op efter sprogafhængighed

### ISSUE THREAD

**Issue by johan-ejstrud** [StatisticsGreenland/pxmake#65]
# FØR
![image](https://user-images.githubusercontent.com/11992346/219025562-78ac94f3-7f96-4b6d-b419-4a2a9a160d4f.png)

# EFTER
![image](https://user-images.githubusercontent.com/11992346/219025480-04236e55-3e34-4bdc-9ce4-8e84b7854fdd.png)

![image](https://user-images.githubusercontent.com/11992346/219025507-b5682eac-195b-4de5-b9f9-06c6c0143849.png)

**Comment by larpSTATGL** [comment]
Det giver en pænere struktur og er lettere at få overblik over. Til mikrodata, som vi ikke har snakket om, er General en enkel transponering. Men det må ogsåkunne løses. Så fint.

**Comment by larpSTATGL** [comment]
Er det en stor ændring i kode? Hvis ikke, kunne det være godt at få det på plads inden jeg laver for mange meta-xlsx

**Comment by larpSTATGL** [comment]
De kunne måske kaldes General og General_text ? Bare forslag, hvis du har andet i tankerne er det også fint

**Comment by johan-ejstrud** [comment]
> Er det en stor ændring i kode? Hvis ikke, kunne det være godt at få det på plads inden jeg laver for mange meta-xlsx
Det er en lille ændring i koden, og vil formentlig gøre det simplere, fordi vi så behandler alle sheets på samme måde.


> De kunne måske kaldes General og General_text ? Bare forslag, hvis du har andet i tankerne er det også fint
Ja, jeg er lidt i tvivl om hvad der er den bedste måde at implementere det på (om det skal være ét eller to sheets), under alle omstændigheder håber jeg vi tydligt kan kommunikere til brugeren om et keyword er sprogafhængigt eller ej.

**Comment by larpSTATGL** [comment]
Nu, hvor du kontrollerer rækkefølge af nøgleord, behøver vi ingen bestemt rækkefølge i disse ark. Måske er alfabetisk orden af nøgleord lettere at orientere sig i?

**Comment by johan-ejstrud** [comment]
> Nu, hvor du kontrollerer rækkefølge af nøgleord, behøver vi ingen bestemt rækkefølge i disse ark. Måske er alfabetisk orden af nøgleord lettere at orientere sig i?

God ide!
