### ISSUE TITLE
Long names in value row aren't used

### ISSUE THREAD

**Issue by johan-ejstrud** [StatisticsGreenland/pxmake#89]
The long names in the variables are not added to the px file. 
![image](https://user-images.githubusercontent.com/11992346/223095681-f6ab84d7-a173-454a-a9cb-f7c98a50fcb7.png)

1. How should these be added?
2. Can the different name(s) of `values` be viewed in PxEdit?

**Comment by larpSTATGL** [comment]
They are not to be included in the px-file

But FIGURES tells what the count column in the DATA is named - here we have 


'place of birth', gender, value
N,F,23
N,M,32
...

if instead DATA was

'place of birth', gender, antal
N,F,23
N,M,32
...

B2 in xlsx should read 'antal' - and we will still know, that antal is FIGURES

:-)

**Comment by johan-ejstrud** [comment]
Closed because of @larpSTATGL explanation.
