### ISSUE TITLE
CODES values should be a combination of data and codelist

### ISSUE THREAD

**Issue by larpSTATGL** [StatisticsGreenland/pxmake#91]
Med Timeval blev CODES til time taget bort fra px fil

Men vi må beholde CODES, så vi altså for 'time' både har 

VALUES("time")
CODES("time")
og 
TIMEVAL("time")

**Comment by johan-ejstrud** [comment]
Hej @larpSTATGL, jeg kiggede lige lidt i historibøgerne, og jeg tror ikke det her var en fejl der blev introduceret da [timeval blev tilføjet](https://github.com/StatisticsGreenland/pxmake/commit/843caac5b18a53fb345601caeb83f36740098c04#diff-178b70e0821071aa0faebffe14556a8710a70675629806ad7357ac5d04a8c207). F.eks. kan jeg se at der i [BEXSTA.px](https://github.com/StatisticsGreenland/pxmake/commit/843caac5b18a53fb345601caeb83f36740098c04#diff-178b70e0821071aa0faebffe14556a8710a70675629806ad7357ac5d04a8c207) ikke blev fjernet nogle CODES linjer, men kun tilføjet TIMEVAL værdier.

Jeg tror derimod fejlen er: _CODES bliver kun tilføjet hvis de står i Codelist_.

Jeg tror derfor CODES skal være en kombination af de værdier der er i data og dem der er i codelist.

**Comment by johan-ejstrud** [comment]
Relaterert: #86 #13

**Comment by larpSTATGL** [comment]
Det giver absolut mening - det skal være en kombo
